<?php

return [
    'semantic-universe-determinants-v1-1' => [
        'title' => 'Semantic Universe Determinants V.1.1.docx',
        'path' => resource_path('semantic-universe-journal/source-files/semantic-universe-determinants-v1-1.docx'),
        'original_path' => 'E:/ARGİM-SAGİM/4 SEMANGER/Semantic Universe Determinants/Semantic Universe Determinants V.1.1.docx',
        'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'category' => 'Kurucu Belge',
        'summary' => 'Semantic Universe determinantlarını ve üst sistem mantığını açıklayan ilk kurucu belge.',
        'roles' => [
            'Ana kaynak',
            'Kurucu belge',
            'Kavramsal çerçeve',
        ],
        'status_note' => null,
    ],
    'saas-kaynak-agaci-mantigi' => [
        'title' => 'SAAS KAYNAK AĞACI MANTIĞI.pptx',
        'path' => resource_path('semantic-universe-journal/source-files/saas-kaynak-agaci-mantigi.pptx'),
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/SAAS KAYNAK AĞACI MANTIĞI.pptx',
        'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'category' => 'Kaynak Mimarisi',
        'summary' => 'SaaS modelinde kaynak ağacı mantığını, kaynakların üst-alt ilişkileri ve modüler kurgusu üzerinden ele alan kurucu sunum.',
        'roles' => [
            'Kaynak dokümanı',
            'Yol haritası',
            'Stratejik yöntem',
        ],
        'status_note' => null,
    ],
    'hbys-kaynak-katmanlari-v2-1' => [
        'title' => 'HBYS KAYNAK_KATMANLARI V.2.1.pdf',
        'path' => resource_path('semantic-universe-journal/source-files/hbys-kaynak-katmanlari-v2-1.pdf'),
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/HBYS KAYNAK_KATMANLARI V.2.1.pdf',
        'mime' => 'application/pdf',
        'category' => 'Kaynak Katmanları',
        'summary' => 'HBYS bağlamında kaynak katmanlarını, kaynakların sınıf ve katman mantığını açıklayan temel referans doküman.',
        'roles' => [
            'Kaynak dokümanı',
            'İlke seti',
            'Referans model',
        ],
        'status_note' => null,
    ],
    'proses-bolumleme-alt-prosesler-standardi' => [
        'title' => 'Proses Bölümleme, Alt Prosesler Tasarlama ve Bu Süreç Ne Yapar İçeriği Oluşturma Standardı.pptx',
        'path' => resource_path('semantic-universe-journal/source-files/proses-bolumleme-alt-prosesler-standardi.pptx'),
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/Proses Bölümleme, Alt Prosesler Tasarlama ve Bu Süreç Ne Yapar İçeriği Oluşturma Standardı.pptx',
        'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'category' => 'Proses Tasarımı',
        'summary' => 'Prosesleri bölümleme, alt proses tasarlama ve süreç açıklama standardını taşıyan uygulama odaklı sunum.',
        'roles' => [
            'Standart',
            'Stratejik yöntem',
            'Eğitici doküman',
        ],
        'status_note' => null,
    ],
    'semanger-yapisal-kavramsal-sunum-v2-2' => [
        'title' => 'Semanger Yapısal Kavramsal Sunum V.2.2.pptx',
        'path' => null,
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/Semanger Yapısal Kavramsal Sunum V.2.2.pptx',
        'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'category' => 'Kavramsal Çerçeve',
        'summary' => 'Semanger yapısal ve kavramsal çerçevesini geniş ölçekte anlatan ana üst sunum seti.',
        'roles' => [
            'Ana kaynak',
            'Kavramsal çerçeve',
            'Yol haritası',
        ],
        'status_note' => 'Bu dosya GitHub sınırını aşan büyük boyutlu bir sunumdur; kataloga işlendi, doğrudan repo arşivine alınmadı. Gerekirse sunucuya ayrı kanaldan yüklenecek.',
    ],
    'parmaklarla-anlatim' => [
        'title' => 'Parmaklarla Anlatım.pptx',
        'path' => resource_path('semantic-universe-journal/source-files/parmaklarla-anlatim.pptx'),
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/Parmaklarla Anlatım.pptx',
        'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'category' => 'Anlatım Modeli',
        'summary' => 'Kavramsal anlatımı daha kolay anlaşılır hâle getiren pedagojik anlatım çerçevesi.',
        'roles' => [
            'Eğitici doküman',
            'Değerler',
            'İletişim yöntemi',
        ],
        'status_note' => null,
    ],
    'saglik-yonetisimi-semanger-21-yuzyil' => [
        'title' => '21. Yüzyılda Sağlık Yönetişimi - Semanger.pptx',
        'path' => resource_path('semantic-universe-journal/source-files/21-yuzyilda-saglik-yonetisimi-semanger.pptx'),
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/21. Yüzyılda Sağlık Yönetişimi - Semanger.pptx',
        'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'category' => 'Yönetişim',
        'summary' => '21. yüzyıl sağlık yönetişimi yaklaşımını Semanger bakış açısıyla kuran stratejik sunum.',
        'roles' => [
            'İlke seti',
            'Değerler',
            'Stratejik yöntem',
        ],
        'status_note' => null,
    ],
    'kut-yolu-ve-duvari' => [
        'title' => 'KUT Yolu ve Duvarı.pptx',
        'path' => resource_path('semantic-universe-journal/source-files/kut-yolu-ve-duvari.pptx'),
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/KUT Yolu ve Duvarı.pptx',
        'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'category' => 'Stratejik Model',
        'summary' => 'KUT yaklaşımını yol ve duvar metaforu üzerinden anlatan kavramsal-stratejik sunum.',
        'roles' => [
            'Stratejik yöntem',
            'Yol haritası',
            'Değerler',
        ],
        'status_note' => null,
    ],
    'is-hayati-bir-yaris-ve-ilerleme-v3-1' => [
        'title' => 'İŞ HAYATI BİR YARIŞ VE İLERLEME V.3.1..pptx',
        'path' => resource_path('semantic-universe-journal/source-files/is-hayati-bir-yaris-ve-ilerleme-v3-1.pptx'),
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/İŞ HAYATI BİR YARIŞ VE İLERLEME V.3.1..pptx',
        'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'category' => 'Kurum Kültürü',
        'summary' => 'İş hayatını yarış, ilerleme ve gelişim ekseninde ele alan kültürel-stratejik sunum.',
        'roles' => [
            'Değerler',
            'İlke seti',
            'Kurum kültürü',
        ],
        'status_note' => null,
    ],
    'alper-surec-v3-2' => [
        'title' => 'Alper Süreç V.3.2.pptx',
        'path' => resource_path('semantic-universe-journal/source-files/alper-surec-v3-2.pptx'),
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/Alper Süreç V.3.2.pptx',
        'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'category' => 'Süreç Mimarisi',
        'summary' => 'Süreç ve alt süreç tasarımını örnekleyen, süreç odaklı düşünmeyi destekleyen çalışma sunumu.',
        'roles' => [
            'Stratejik yöntem',
            'Süreç standardı',
            'Eğitici doküman',
        ],
        'status_note' => null,
    ],
    'toplanti-yonetimi-slayt' => [
        'title' => 'TOPLANTI YÖNETİMİ SLAYT.pptx',
        'path' => resource_path('semantic-universe-journal/source-files/toplanti-yonetimi-slayt.pptx'),
        'original_path' => 'E:/ARGİM-SAGİM/5 SEMANTİK HASTANE YÖNETİMİ/Sunumlar Semantik Hastane/TOPLANTI YÖNETİMİ SLAYT.pptx',
        'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'category' => 'Toplantı Yönetimi',
        'summary' => 'Toplantı yönetimi, karar üretimi ve çalışma disiplini için referans alınacak temel sunum.',
        'roles' => [
            'Standart',
            'Yönetim yöntemi',
            'Eğitici doküman',
        ],
        'status_note' => null,
    ],
];

